
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "numZ : SexpSexp : '(' '+' Lista ')'Sexp : '(' '*' Lista ')'Sexp : numLista : Lista SexpLista : Sexp Sexp"
    
_lr_action_items = {'(':([0,4,5,6,7,8,9,10,11,12,13,],[3,-4,3,3,3,3,3,-2,-5,-6,-3,]),'num':([0,4,5,6,7,8,9,10,11,12,13,],[4,-4,4,4,4,4,4,-2,-5,-6,-3,]),'$end':([1,2,4,10,13,],[0,-1,-4,-2,-3,]),'+':([3,],[5,]),'*':([3,],[6,]),')':([4,7,9,10,11,12,13,],[-4,10,13,-2,-5,-6,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Z':([0,],[1,]),'Sexp':([0,5,6,7,8,9,],[2,8,8,11,12,11,]),'Lista':([5,6,],[7,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Z","S'",1,None,None,None),
  ('Z -> Sexp','Z',1,'p_Z','pl05.py',50),
  ('Sexp -> ( + Lista )','Sexp',4,'p_Sexp_ad','pl05.py',54),
  ('Sexp -> ( * Lista )','Sexp',4,'p_Sexp_mul','pl05.py',58),
  ('Sexp -> num','Sexp',1,'p_Sexp_num','pl05.py',62),
  ('Lista -> Lista Sexp','Lista',2,'p_Lista_ls','pl05.py',66),
  ('Lista -> Sexp Sexp','Lista',2,'p_Lista_ss','pl05.py',70),
]
