
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "left+-left*/rightUMINUSNUMBER VAR stat : VAR '=' exp  stat : exp  exp : exp '+' exp  exp : exp '-' exp  exp : exp '*' exp  exp : exp '/' exp  exp : '-' exp %prec UMINUS  exp : '(' exp ')'  exp : NUMBER  exp : VAR "
    
_lr_action_items = {'VAR':([0,4,5,7,8,9,10,11,],[2,13,13,13,13,13,13,13,]),'-':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[4,-10,9,4,4,-9,4,4,4,4,4,-7,-10,9,9,-3,-4,-5,-6,-8,]),'(':([0,4,5,7,8,9,10,11,],[5,5,5,5,5,5,5,5,]),'NUMBER':([0,4,5,7,8,9,10,11,],[6,6,6,6,6,6,6,6,]),'$end':([1,2,3,6,12,13,15,16,17,18,19,20,],[0,-10,-2,-9,-7,-10,-1,-3,-4,-5,-6,-8,]),'=':([2,],[7,]),'+':([2,3,6,12,13,14,15,16,17,18,19,20,],[-10,8,-9,-7,-10,8,8,-3,-4,-5,-6,-8,]),'*':([2,3,6,12,13,14,15,16,17,18,19,20,],[-10,10,-9,-7,-10,10,10,10,10,-5,-6,-8,]),'/':([2,3,6,12,13,14,15,16,17,18,19,20,],[-10,11,-9,-7,-10,11,11,11,11,-5,-6,-8,]),')':([6,12,13,14,16,17,18,19,20,],[-9,-7,-10,20,-3,-4,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stat':([0,],[1,]),'exp':([0,4,5,7,8,9,10,11,],[3,12,14,15,16,17,18,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stat","S'",1,None,None,None),
  ('stat -> VAR = exp','stat',3,'p_stat_0','calculator_build.py',33),
  ('stat -> exp','stat',1,'p_stat_1','calculator_build.py',37),
  ('exp -> exp + exp','exp',3,'p_exp_2','calculator_build.py',41),
  ('exp -> exp - exp','exp',3,'p_exp_3','calculator_build.py',45),
  ('exp -> exp * exp','exp',3,'p_exp_4','calculator_build.py',49),
  ('exp -> exp / exp','exp',3,'p_exp_5','calculator_build.py',53),
  ('exp -> - exp','exp',2,'p_exp_6','calculator_build.py',57),
  ('exp -> ( exp )','exp',3,'p_exp_7','calculator_build.py',61),
  ('exp -> NUMBER','exp',1,'p_exp_8','calculator_build.py',65),
  ('exp -> VAR','exp',1,'p_exp_9','calculator_build.py',69),
]
